services:
  server:
    build:
      context: ./server
    container_name: scribe_server
    restart: always
    ports:
      - "9000:8000"
    env_file:
      - .env
    networks:
      - scribe_network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]  # Production mode without --reload

networks:
  scribe_network: