name: Scribe CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.check.outputs.backend_changed }}
      frontend_changed: ${{ steps.check.outputs.frontend_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for Backend and Frontend Changes
        id: check
        run: |
          git fetch origin main
          BACKEND_CHANGED=false
          FRONTEND_CHANGED=false
          if git diff --name-only origin/main | grep '^server/'; then
            BACKEND_CHANGED=true
          fi
          if git diff --name-only origin/main | grep '^client/'; then
            FRONTEND_CHANGED=true
          fi
          echo "backend_changed=$BACKEND_CHANGED" >> $GITHUB_OUTPUT
          echo "frontend_changed=$FRONTEND_CHANGED" >> $GITHUB_OUTPUT

  backend-tests:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Execute Backend Tests
        run: PYTHONPATH=./server pytest

  frontend-tests:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Execute Frontend Tests
        working-directory: ./client
        run: npm test
