name: Scribe CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set Up Python Environment
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Determine Changed Files
        id: changed-files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Execute Backend Tests for Changed Files
        run: |
          TEST_FILES=$(echo "${{ steps.changed-files.outputs.changed_files }}" | grep '^server/tests/' | grep '_test\.py$' || true)
          if [ -z "$TEST_FILES" ]; then
            echo "No backend test files changed. Skipping tests."
          else
            echo "Running backend tests for changed files: $TEST_FILES"
            PYTHONPATH=./server pytest $TEST_FILES
          fi

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Determine Changed Files
        id: frontend-changed-files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Execute Frontend Tests for Changed Files
        working-directory: ./client
        run: |
          TEST_COMPONENTS=$(echo "${{ steps.frontend-changed-files.outputs.changed_files }}" | grep '^client/__tests__/' | grep '\.test\.[jt]sx$' || true)
          if [ -z "$TEST_COMPONENTS" ]; then
            echo "No frontend test files changed. Skipping tests."
          else
            echo "Running frontend tests for changed components: $TEST_COMPONENTS"
            npm test -- $TEST_COMPONENTS
          fi
